/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as MeusCampeonatosRouteImport } from './routes/meus-campeonatos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as InscricaoTournamentIdRouteImport } from './routes/inscricao.$tournamentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCampeonatosRoute = MeusCampeonatosRouteImport.update({
  id: '/meus-campeonatos',
  path: '/meus-campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTournamentIdRoute = InscricaoTournamentIdRouteImport.update({
  id: '/inscricao/$tournamentId',
  path: '/inscricao/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jogar': typeof JogarRoute
  '/meus-campeonatos': typeof MeusCampeonatosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/inscricao/$tournamentId': typeof InscricaoTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jogar': typeof JogarRoute
  '/meus-campeonatos': typeof MeusCampeonatosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/inscricao/$tournamentId': typeof InscricaoTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jogar': typeof JogarRoute
  '/meus-campeonatos': typeof MeusCampeonatosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/inscricao/$tournamentId': typeof InscricaoTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jogar'
    | '/meus-campeonatos'
    | '/perfil'
    | '/ranking'
    | '/inscricao/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jogar'
    | '/meus-campeonatos'
    | '/perfil'
    | '/ranking'
    | '/inscricao/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/jogar'
    | '/meus-campeonatos'
    | '/perfil'
    | '/ranking'
    | '/inscricao/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JogarRoute: typeof JogarRoute
  MeusCampeonatosRoute: typeof MeusCampeonatosRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  InscricaoTournamentIdRoute: typeof InscricaoTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-campeonatos': {
      id: '/meus-campeonatos'
      path: '/meus-campeonatos'
      fullPath: '/meus-campeonatos'
      preLoaderRoute: typeof MeusCampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$tournamentId': {
      id: '/inscricao/$tournamentId'
      path: '/inscricao/$tournamentId'
      fullPath: '/inscricao/$tournamentId'
      preLoaderRoute: typeof InscricaoTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JogarRoute: JogarRoute,
  MeusCampeonatosRoute: MeusCampeonatosRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  InscricaoTournamentIdRoute: InscricaoTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
